import type { Metadata } from "next";
import { Saira_Condensed, Poppins, Bebas_Neue } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["200", "300", "400"],
});

const saira = Saira_Condensed({
  variable: "--font-saira",
  weight: ["200", "300"],
});

const bebas = Bebas_Neue({
  variable: "--font-bebas",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Discord clone",
  description: "Generated by create next app",
};

// theme provider
import { ThemeProvider } from "@/components/providers/theme-provider";

// clerk auth
import { ClerkProvider } from "@clerk/nextjs";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} ${saira.variable} ${bebas.variable}`}
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={false}
            storageKey="discord-clone-theme"
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
